name: misspell_checker

on:
  pull_request:
    types:
      - opened

jobs:
  mis_spell_check_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rsvn *'
    - uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'Fixes by misspell-fixer'
        base: ${{ github.head_ref }}
        title: 'Typos fix by misspell-fixer'
        labels: |
          ci_skip